(source melpa)

(depends-on "auto-complete")
(depends-on "flycheck")
(depends-on "helm")
(depends-on "helm-c-yasnippet")
(depends-on "helm-ls-git")
(depends-on "helm-git-grep")
(depends-on "magit")
(depends-on "popwin")
(depends-on "smartparens")
(depends-on "yasnippet")
(depends-on "undo-tree")
(depends-on "multiple-cursors")
(depends-on "coffee-mode")
(depends-on "jade-mode")
(depends-on "feature-mode")
(depends-on "coffee-mode")
(depends-on "sws-mode")
(depends-on "less-css-mode")
(depends-on "scss-mode")
(depends-on "flymake-easy")


